import { Injectable } from '@angular/core';
import { ProductApiClient } from './product-api-client.interface';
import { Product } from '../models/product.model';

@Injectable({
  providedIn: 'root',
})
export class MockProductApiClientService implements ProductApiClient {
  private products: Product[] = [
    {
      id: 1,
      brand: 'Fender',
      model: 'Stratocaster',
      color: 'Sunburst',
      description: 'Классическая электрогитара с уникальным звучанием.',
      price: 120000,
      imageUrl: 'https://images.musicstore.de/images/0960/fender-player-ii-stratocaster-rw-3-color-sunburst_1_GIT0061901-001.jpg',
      categoryId: 2,
    },
    {
      id: 2,
      brand: 'Gibson',
      model: 'Les Paul Standard',
      color: 'Cherry Sunburst',
      description: 'Легендарная гитара для рок-музыки.',
      price: 150000,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 3,
      brand: 'Ibanez',
      model: 'RG550',
      color: 'Purple Neon',
      description: 'Высококачественная электрогитара для метала.',
      price: 95000,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 4,
      brand: 'Yamaha',
      model: 'FG800',
      color: 'Natural',
      description: 'Отличная акустическая гитара для начинающих.',
      price: 25000,
      imageUrl: '',
      categoryId: 3,
    },
    {
      id: 5,
      brand: 'Epiphone',
      model: 'Les Paul Studio',
      color: 'Black',
      description: 'Доступная версия легендарной модели Gibson.',
      price: 40000,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 6,
      brand: 'DW',
      model: 'Performance Series',
      color: 'Black Oyster',
      description: 'Профессиональная ударная установка.',
      price: 450000,
      imageUrl: '',
      categoryId: 5,
    },
    {
      id: 7,
      brand: 'Tama',
      model: 'Imperialstar',
      color: 'Hairline Blue',
      description: 'Идеальная ударная установка для начинающих.',
      price: 90000,
      imageUrl: '',
      categoryId: 5,
    },
    {
      id: 8,
      brand: 'Zildjian',
      model: 'A Custom Cymbal Pack',
      color: 'Brilliant',
      description: 'Профессиональный комплект тарелок.',
      price: 120000,
      imageUrl: '',
      categoryId: 5,
    },
    {
      id: 9,
      brand: 'Roland',
      model: 'TD-17KVX',
      color: 'Black',
      description: 'Электронная ударная установка с реалистичным звучанием.',
      price: 220000,
      imageUrl: '',
      categoryId: 5,
    },
    {
      id: 10,
      brand: 'Korg',
      model: 'B2',
      color: 'White',
      description: 'Электронное пианино для домашнего использования.',
      price: 45000,
      imageUrl: '',
      categoryId: 6,
    },
    {
      id: 11,
      brand: 'Casio',
      model: 'CT-X700',
      color: 'Black',
      description: 'Синтезатор с отличным функционалом.',
      price: 25000,
      imageUrl: '',
      categoryId: 6,
    },
    {
      id: 12,
      brand: 'Yamaha',
      model: 'P-45',
      color: 'Black',
      description: 'Компактное цифровое пианино.',
      price: 40000,
      imageUrl: '',
      categoryId: 6,
    },
    {
      id: 13,
      brand: 'Boss',
      model: 'Katana-50 MkII',
      color: 'Black',
      description: 'Комбоусилитель для электрогитар.',
      price: 30000,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 14,
      brand: 'Marshall',
      model: 'MG30GFX',
      color: 'Black/Gold',
      description: 'Комбоусилитель с эффектами.',
      price: 35000,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 15,
      brand: 'PRS',
      model: 'SE Custom 24',
      color: 'Blue Matteo',
      description: 'Премиальная электрогитара по доступной цене.',
      price: 120000,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 16,
      brand: 'Taylor',
      model: '214ce',
      color: 'Natural',
      description: 'Профессиональная акустическая гитара.',
      price: 180000,
      imageUrl: '',
      categoryId: 3,
    },
    {
      id: 17,
      brand: 'Fender',
      model: 'American Professional II Stratocaster',
      color: '3-Color Sunburst',
      description: 'Профессиональная версия Stratocaster.',
      price: 180000,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 18,
      brand: 'D\'Addario',
      model: 'EXL110',
      color: 'Nickel Wound',
      description: 'Комплект струн для электрогитары.',
      price: 800,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 19,
      brand: 'Ernie Ball',
      model: 'Super Slinky',
      color: 'Pink',
      description: 'Популярный комплект струн для электрогитары.',
      price: 900,
      imageUrl: '',
      categoryId: 2,
    },
    {
      id: 20,
      brand: 'Fender',
      model: 'Acoustic 100',
      color: 'Natural',
      description: 'Комбоусилитель для акустической гитары.',
      price: 70000,
      imageUrl: '',
      categoryId: 3,
    },
  ];

  async getProducts(): Promise<Product[]> {
    return this.products;
  }
}
